
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents",
  "version": "0.0.7",
  "versions": {
    "@openai/agents": "0.0.7",
    "@openai/agents-core": "workspace:*",
    "@openai/agents-openai": "workspace:*",
    "@openai/agents-realtime": "workspace:*",
    "openai": "^5.0.1"
  }
};

export default METADATA;
