
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-openai",
  "version": "0.1.3",
  "versions": {
    "@openai/agents-openai": "0.1.3",
    "@openai/agents-core": "workspace:*",
    "openai": "^5.20.2"
  }
};

export default METADATA;
