
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-core",
  "version": "0.0.16",
  "versions": {
    "@openai/agents-core": "0.0.16",
    "openai": "^5.10.1"
  }
};

export default METADATA;
