
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-core",
  "version": "0.0.7",
  "versions": {
    "@openai/agents-core": "0.0.7",
    "@openai/zod": "npm:zod@^3.25.40",
    "openai": "^5.0.1"
  }
};

export default METADATA;
