
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-extensions",
  "version": "0.0.7",
  "versions": {
    "@openai/agents-extensions": "0.0.7",
    "@openai/zod": "npm:zod@^3.25.40"
  }
};

export default METADATA;
