
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-extensions",
  "version": "0.1.2",
  "versions": {
    "@openai/agents-extensions": "0.1.2"
  }
};

export default METADATA;
