
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-extensions",
  "version": "0.1.5",
  "versions": {
    "@openai/agents-extensions": "0.1.5"
  }
};

export default METADATA;
